// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service.proto

package proto // import "./"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Request struct {
	Version              string   `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Method               string   `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`
	Submethod            string   `protobuf:"bytes,3,opt,name=submethod,proto3" json:"submethod,omitempty"`
	Extmethod            string   `protobuf:"bytes,4,opt,name=extmethod,proto3" json:"extmethod,omitempty"`
	Data                 string   `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`
	Header               *Header  `protobuf:"bytes,6,opt,name=header,proto3" json:"header,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_319da7e580552480, []int{0}
}
func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (dst *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(dst, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *Request) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

func (m *Request) GetSubmethod() string {
	if m != nil {
		return m.Submethod
	}
	return ""
}

func (m *Request) GetExtmethod() string {
	if m != nil {
		return m.Extmethod
	}
	return ""
}

func (m *Request) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

func (m *Request) GetHeader() *Header {
	if m != nil {
		return m.Header
	}
	return nil
}

type Response struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data                 string   `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_319da7e580552480, []int{1}
}
func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (dst *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(dst, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Response) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *Response) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

type Header struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Ip                   string   `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Header) Reset()         { *m = Header{} }
func (m *Header) String() string { return proto.CompactTextString(m) }
func (*Header) ProtoMessage()    {}
func (*Header) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_319da7e580552480, []int{2}
}
func (m *Header) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Header.Unmarshal(m, b)
}
func (m *Header) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Header.Marshal(b, m, deterministic)
}
func (dst *Header) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Header.Merge(dst, src)
}
func (m *Header) XXX_Size() int {
	return xxx_messageInfo_Header.Size(m)
}
func (m *Header) XXX_DiscardUnknown() {
	xxx_messageInfo_Header.DiscardUnknown(m)
}

var xxx_messageInfo_Header proto.InternalMessageInfo

func (m *Header) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *Header) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func init() {
	proto.RegisterType((*Request)(nil), "protos.Request")
	proto.RegisterType((*Response)(nil), "protos.Response")
	proto.RegisterType((*Header)(nil), "protos.Header")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CallServiceClient is the client API for CallService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CallServiceClient interface {
	CallService(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type callServiceClient struct {
	cc *grpc.ClientConn
}

func NewCallServiceClient(cc *grpc.ClientConn) CallServiceClient {
	return &callServiceClient{cc}
}

func (c *callServiceClient) CallService(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/protos.CallService/callService", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CallServiceServer is the server API for CallService service.
type CallServiceServer interface {
	CallService(context.Context, *Request) (*Response, error)
}

func RegisterCallServiceServer(s *grpc.Server, srv CallServiceServer) {
	s.RegisterService(&_CallService_serviceDesc, srv)
}

func _CallService_CallService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CallServiceServer).CallService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.CallService/CallService",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CallServiceServer).CallService(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

var _CallService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protos.CallService",
	HandlerType: (*CallServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "callService",
			Handler:    _CallService_CallService_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}

func init() { proto.RegisterFile("service.proto", fileDescriptor_service_319da7e580552480) }

var fileDescriptor_service_319da7e580552480 = []byte{
	// 263 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x91, 0x31, 0x4f, 0xc3, 0x30,
	0x10, 0x85, 0x49, 0xda, 0xb8, 0xed, 0x45, 0x14, 0x74, 0x42, 0xc8, 0x42, 0x0c, 0x55, 0x06, 0xd4,
	0x29, 0x48, 0x61, 0x64, 0x02, 0x16, 0x06, 0x26, 0xb3, 0xb1, 0xb9, 0xc9, 0x89, 0x46, 0xb4, 0x75,
	0xc8, 0xb9, 0x15, 0xff, 0x8b, 0x3f, 0x88, 0x62, 0x3b, 0x09, 0x93, 0xef, 0xbd, 0x4f, 0xba, 0x7b,
	0x77, 0x86, 0x73, 0xa6, 0xf6, 0x54, 0x97, 0x94, 0x37, 0xad, 0xb1, 0x06, 0x85, 0x7b, 0x38, 0xfb,
	0x8d, 0x60, 0xa6, 0xe8, 0xfb, 0x48, 0x6c, 0x51, 0xc2, 0xec, 0x44, 0x2d, 0xd7, 0xe6, 0x20, 0xa3,
	0x55, 0xb4, 0x5e, 0xa8, 0x5e, 0xe2, 0x35, 0x88, 0x3d, 0xd9, 0xad, 0xa9, 0x64, 0xec, 0x40, 0x50,
	0x78, 0x0b, 0x0b, 0x3e, 0x6e, 0x02, 0x9a, 0x38, 0x34, 0x1a, 0x1d, 0xa5, 0x1f, 0x1b, 0xe8, 0xd4,
	0xd3, 0xc1, 0x40, 0x84, 0x69, 0xa5, 0xad, 0x96, 0x89, 0x03, 0xae, 0xc6, 0x3b, 0x10, 0x5b, 0xd2,
	0x15, 0xb5, 0x52, 0xac, 0xa2, 0x75, 0x5a, 0x2c, 0x7d, 0x5a, 0xce, 0x5f, 0x9d, 0xab, 0x02, 0xcd,
	0xde, 0x60, 0xae, 0x88, 0x1b, 0x73, 0x60, 0xea, 0xfa, 0x94, 0xa6, 0x22, 0x17, 0x39, 0x51, 0xae,
	0xee, 0x36, 0xd9, 0x13, 0xb3, 0xfe, 0xa4, 0x10, 0xb8, 0x97, 0xc3, 0xd4, 0xc9, 0x38, 0x35, 0xcb,
	0x41, 0xf8, 0xfe, 0x78, 0x05, 0x89, 0x35, 0x5f, 0xd4, 0xef, 0xef, 0x05, 0x2e, 0x21, 0xae, 0x9b,
	0xd0, 0x28, 0xae, 0x9b, 0xe2, 0x09, 0xd2, 0x17, 0xbd, 0xdb, 0xbd, 0xfb, 0x83, 0x62, 0x01, 0x69,
	0xf9, 0x4f, 0x5e, 0xf4, 0x99, 0xc3, 0x59, 0x6f, 0x2e, 0x47, 0xc3, 0x47, 0xce, 0xce, 0x9e, 0xe1,
	0x63, 0x9e, 0xdf, 0x3f, 0x3a, 0x7f, 0xe3, 0xbf, 0xe2, 0xe1, 0x2f, 0x00, 0x00, 0xff, 0xff, 0xc9,
	0x09, 0xfc, 0x38, 0xa2, 0x01, 0x00, 0x00,
}
